-- 005_chat_nullable_project.sql — allow project-independent chat sessions
--
-- Changes:
--   1. project_id becomes nullable (NULL = "general" chat, not tied to a project)
--   2. FK changes from ON DELETE CASCADE to ON DELETE SET NULL
--      (deleting a project preserves chat history instead of wiping it)
--
-- The FK constraint name is auto-generated by PostgreSQL as
-- "chat_sessions_project_id_fkey".

-- Drop NOT NULL constraint.
ALTER TABLE chat_sessions ALTER COLUMN project_id DROP NOT NULL;

-- Replace the FK: CASCADE -> SET NULL.
ALTER TABLE chat_sessions
    DROP CONSTRAINT IF EXISTS chat_sessions_project_id_fkey;

ALTER TABLE chat_sessions
    ADD CONSTRAINT chat_sessions_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL;
