//! Lightweight browser routes for Drive-hosted HTML files.
//!
//! HTML generated by agents is executable content, so it is intentionally not
//! served through the generic Drive blob endpoint. These routes keep rendering
//! behind a narrow Drive-path policy, rewrite relative resources through the
//! same policy boundary, and send iframe-focused headers that prevent the page
//! from reaching back into the main mymy application.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use axum::body::Body;
use axum::extract::{Path as AxumPath, Query, State};
use axum::http::{header, HeaderValue};
use axum::response::Response;
use axum::routing::get;
use axum::Router;
use serde::Deserialize;

use crate::error::{AppError, AppResult};
use crate::models::drive::DrivePathQuery;
use crate::services::drive;
use crate::state::AppState;

#[derive(Debug, Deserialize)]
pub struct WebViewerAssetQuery {
    pub root: String,
}

pub fn routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/web-viewer/drive", get(read_drive_html))
        .route("/api/web-viewer/assets/{*asset}", get(read_drive_asset))
}

pub async fn read_drive_html(
    State(state): State<Arc<AppState>>,
    Query(query): Query<DrivePathQuery>,
) -> AppResult<Response> {
    let path = query.path.unwrap_or_else(|| "/drive".to_string());
    let resolved = drive::resolve_drive_path(&state.config.agent_data_dir, &path)?;
    let metadata = std::fs::metadata(&resolved.physical_path)?;
    if !metadata.is_file() || !is_html_path(&resolved.physical_path) {
        return Err(AppError::BadRequest(
            "Drive path is not an HTML file".into(),
        ));
    }
    let html = tokio::fs::read_to_string(&resolved.physical_path).await?;
    let root = parent_logical_path(&resolved.logical_path)?;
    let html = rewrite_html_for_viewer(&html, &root);
    html_response(html)
}

pub async fn read_drive_asset(
    State(state): State<Arc<AppState>>,
    AxumPath(asset): AxumPath<String>,
    Query(query): Query<WebViewerAssetQuery>,
) -> AppResult<Response> {
    let logical_path = resolve_asset_logical_path(&query.root, &asset)?;
    let resolved = drive::resolve_drive_path(&state.config.agent_data_dir, &logical_path)?;
    let metadata = std::fs::metadata(&resolved.physical_path)?;
    if !metadata.is_file() {
        return Err(AppError::NotFound(format!("asset {asset} not found")));
    }
    if is_html_path(&resolved.physical_path) {
        let html = tokio::fs::read_to_string(&resolved.physical_path).await?;
        let root = parent_logical_path(&resolved.logical_path)?;
        return html_response(rewrite_html_for_viewer(&html, &root));
    }
    let bytes = tokio::fs::read(&resolved.physical_path).await?;
    let content_type = HeaderValue::from_static(drive::mime_type_for_path(&resolved.physical_path));
    let mut response = Response::new(Body::from(bytes));
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, content_type);
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("no-store, max-age=0"),
    );
    response.headers_mut().insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    Ok(response)
}

fn html_response(html: String) -> AppResult<Response> {
    let mut response = Response::new(Body::from(html));
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("text/html; charset=utf-8"),
    );
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("no-store, max-age=0"),
    );
    response.headers_mut().insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    response.headers_mut().insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(
            "default-src 'self' data: blob:; script-src 'self' 'unsafe-inline' data: blob:; style-src 'self' 'unsafe-inline' data: blob:; img-src 'self' data: blob:; media-src 'self' data: blob:; font-src 'self' data: blob:; connect-src 'none'; frame-ancestors 'self'; base-uri 'none'; form-action 'none'",
        ),
    );
    Ok(response)
}

fn rewrite_html_for_viewer(html: &str, root: &str) -> String {
    let mut output = html.to_string();
    for attr in ["src", "href", "poster"] {
        output = rewrite_html_attribute(&output, attr, root);
    }
    inject_viewer_bootstrap(&output)
}

fn rewrite_html_attribute(html: &str, attr: &str, root: &str) -> String {
    let mut current = html.to_string();
    for quote in ['"', '\''] {
        let mut output = String::new();
        let marker = format!("{attr}={quote}");
        let mut rest = current.as_str();
        while let Some(start) = rest.find(&marker) {
            output.push_str(&rest[..start]);
            output.push_str(&marker);
            let value_start = start + marker.len();
            let after_value_start = &rest[value_start..];
            let Some(value_end) = after_value_start.find(quote) else {
                output.push_str(after_value_start);
                return output;
            };
            let value = &after_value_start[..value_end];
            output.push_str(&rewrite_html_url(attr, value, root));
            rest = &after_value_start[value_end..];
        }
        output.push_str(rest);
        current = output;
    }
    current
}

fn rewrite_html_url(attr: &str, value: &str, root: &str) -> String {
    if should_leave_url(value) {
        return value.to_string();
    }
    if attr.eq_ignore_ascii_case("href") && is_external_web_url(value) {
        return value.to_string();
    }
    let Ok(logical_path) = resolve_asset_logical_path(root, value) else {
        return "about:blank".to_string();
    };
    let relative = logical_path
        .trim_start_matches(root)
        .trim_start_matches('/')
        .to_string();
    format!(
        "/api/web-viewer/assets/{}?root={}",
        encode_asset_path(&relative),
        urlencoding::encode(root)
    )
}

fn is_external_web_url(value: &str) -> bool {
    let lower = value.trim().to_ascii_lowercase();
    lower.starts_with("http://") || lower.starts_with("https://") || lower.starts_with("//")
}

fn should_leave_url(value: &str) -> bool {
    let lower = value.trim().to_ascii_lowercase();
    lower.is_empty()
        || lower.starts_with('#')
        || lower.starts_with("data:")
        || lower.starts_with("blob:")
        || lower.starts_with("mailto:")
        || lower.starts_with("tel:")
}

fn inject_viewer_bootstrap(html: &str) -> String {
    const SCRIPT: &str = r#"<script>
(() => {
  document.addEventListener("click", (event) => {
    const anchor = event.target && event.target.closest ? event.target.closest("a[href]") : null;
    if (!anchor) return;
    const href = anchor.href;
    if (!href) return;
    event.preventDefault();
    window.parent.postMessage({ type: "mymy-web-viewer:navigate", href }, "*");
  }, true);
})();
</script>"#;
    if let Some(index) = html.rfind("</body>") {
        let mut output = String::new();
        output.push_str(&html[..index]);
        output.push_str(SCRIPT);
        output.push_str(&html[index..]);
        output
    } else {
        format!("{html}{SCRIPT}")
    }
}

fn resolve_asset_logical_path(root: &str, asset: &str) -> AppResult<String> {
    let normalized_root = drive::normalize_logical_drive_path(root)?;
    if asset.contains('\\') {
        return Err(AppError::BadRequest("Invalid asset path".into()));
    }
    if asset.starts_with("http://") || asset.starts_with("https://") || asset.starts_with("//") {
        return Err(AppError::BadRequest(
            "External asset URLs are blocked".into(),
        ));
    }
    let path_without_query = asset.split(['?', '#']).next().unwrap_or_default();
    let decoded = percent_decode(path_without_query)?;
    let mut path = PathBuf::from(&normalized_root);
    for component in Path::new(&decoded).components() {
        match component {
            std::path::Component::Normal(part) => path.push(part),
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                return Err(AppError::BadRequest(
                    "Asset path escapes viewer root".into(),
                ));
            }
            std::path::Component::RootDir | std::path::Component::Prefix(_) => {
                return Err(AppError::BadRequest(
                    "Absolute asset paths are blocked".into(),
                ));
            }
        }
    }
    let logical = path
        .to_string_lossy()
        .replace('\\', "/")
        .trim_end_matches('/')
        .to_string();
    if logical == normalized_root || logical.starts_with(&format!("{normalized_root}/")) {
        drive::normalize_logical_drive_path(&logical)
    } else {
        Err(AppError::BadRequest(
            "Asset path escapes viewer root".into(),
        ))
    }
}

fn parent_logical_path(path: &str) -> AppResult<String> {
    let normalized = drive::normalize_logical_drive_path(path)?;
    let parent = normalized
        .rsplit_once('/')
        .map(|(parent, _)| parent)
        .unwrap_or(drive::DRIVE_PREFIX);
    if parent.is_empty() {
        Ok(drive::DRIVE_PREFIX.to_string())
    } else {
        Ok(parent.to_string())
    }
}

fn is_html_path(path: &Path) -> bool {
    path.extension()
        .and_then(|value| value.to_str())
        .is_some_and(|extension| {
            extension.eq_ignore_ascii_case("html") || extension.eq_ignore_ascii_case("htm")
        })
}

fn encode_asset_path(path: &str) -> String {
    path.split('/')
        .map(urlencoding::encode)
        .collect::<Vec<_>>()
        .join("/")
}

fn percent_decode(value: &str) -> AppResult<String> {
    percent_encoding::percent_decode_str(value)
        .decode_utf8()
        .map(|value| value.to_string())
        .map_err(|_| AppError::BadRequest("Invalid asset path encoding".into()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_relative_asset_under_root() {
        assert_eq!(
            resolve_asset_logical_path("/drive/agents/elena/site", "css/app.css").unwrap(),
            "/drive/agents/elena/site/css/app.css"
        );
    }

    #[test]
    fn rejects_asset_parent_escape() {
        assert!(resolve_asset_logical_path("/drive/agents/elena/site", "../secret.txt").is_err());
    }

    #[test]
    fn rewrites_relative_html_urls_to_asset_route() {
        let html = r#"<link href="style.css"><script src='app.js'></script>"#;
        let rewritten = rewrite_html_for_viewer(html, "/drive/agents/elena/site");
        assert!(rewritten.contains(
            r#"href="/api/web-viewer/assets/style.css?root=%2Fdrive%2Fagents%2Felena%2Fsite""#
        ));
        assert!(rewritten.contains(
            r#"src='/api/web-viewer/assets/app.js?root=%2Fdrive%2Fagents%2Felena%2Fsite'"#
        ));
        assert!(rewritten.contains("mymy-web-viewer:navigate"));
    }

    #[test]
    fn keeps_external_href_but_blocks_external_resources() {
        let html = r#"<a href="https://example.com/page">open</a><img src="https://example.com/a.png"><script src="//example.com/app.js"></script>"#;
        let rewritten = rewrite_html_for_viewer(html, "/drive/agents/elena/site");

        assert!(rewritten.contains(r#"href="https://example.com/page""#));
        assert!(rewritten.contains(r#"src="about:blank""#));
        assert!(rewritten.contains(r#"src="about:blank""#));
    }
}
