import type { SpreadsheetFormulaFunction } from "./spreadsheetFormulaTypes";

export const SPREADSHEET_MATH_FORMULA_FUNCTIONS: SpreadsheetFormulaFunction[] = [
  {
    name: "SUM",
    signature: "SUM(number1, [number2], ...)",
    description: "Adds numbers, cell references, and ranges.",
    category: "Math",
  },
  {
    name: "AVERAGE",
    signature: "AVERAGE(number1, [number2], ...)",
    description: "Returns the arithmetic mean of numeric arguments.",
    category: "Math",
  },
  {
    name: "COUNT",
    signature: "COUNT(value1, [value2], ...)",
    description: "Counts numeric values.",
    category: "Math",
  },
  {
    name: "COUNTA",
    signature: "COUNTA(value1, [value2], ...)",
    description: "Counts non-empty values.",
    category: "Math",
  },
  {
    name: "MIN",
    signature: "MIN(number1, [number2], ...)",
    description: "Returns the smallest numeric value.",
    category: "Math",
  },
  {
    name: "MAX",
    signature: "MAX(number1, [number2], ...)",
    description: "Returns the largest numeric value.",
    category: "Math",
  },
  {
    name: "ABS",
    signature: "ABS(number)",
    description: "Returns the absolute value.",
    category: "Math",
  },
  {
    name: "ROUND",
    signature: "ROUND(number, digits)",
    description: "Rounds a number to a fixed number of digits.",
    category: "Math",
  },
  {
    name: "ROUNDUP",
    signature: "ROUNDUP(number, digits)",
    description: "Rounds a number away from zero.",
    category: "Math",
  },
  {
    name: "ROUNDDOWN",
    signature: "ROUNDDOWN(number, digits)",
    description: "Rounds a number toward zero.",
    category: "Math",
  },
  {
    name: "POWER",
    signature: "POWER(number, power)",
    description: "Raises a number to a power.",
    category: "Math",
  },
  {
    name: "SQRT",
    signature: "SQRT(number)",
    description: "Returns the square root.",
    category: "Math",
  },
  {
    name: "PRODUCT",
    signature: "PRODUCT(number1, [number2], ...)",
    description: "Multiplies numeric arguments.",
    category: "Math",
  },
  {
    name: "MEDIAN",
    signature: "MEDIAN(number1, [number2], ...)",
    description: "Returns the median numeric value.",
    category: "Math",
  },
  {
    name: "MOD",
    signature: "MOD(number, divisor)",
    description: "Returns the remainder after division.",
    category: "Math",
  },
  {
    name: "INT",
    signature: "INT(number)",
    description: "Rounds a number down to the nearest integer.",
    category: "Math",
  },
  {
    name: "CEILING",
    signature: "CEILING(number, [significance])",
    description: "Rounds a number up to a multiple.",
    category: "Math",
  },
  {
    name: "FLOOR",
    signature: "FLOOR(number, [significance])",
    description: "Rounds a number down to a multiple.",
    category: "Math",
  },
  {
    name: "SUMSQ",
    signature: "SUMSQ(number1, [number2], ...)",
    description: "Returns the sum of squares.",
    category: "Math",
  },
  {
    name: "SUMIF",
    signature: "SUMIF(range, criteria, [sum_range])",
    description: "Adds values whose matching range entries satisfy a criteria expression.",
    category: "Math",
  },
  {
    name: "SUMIFS",
    signature: "SUMIFS(sum_range, criteria_range1, criteria1, ...)",
    description: "Adds values that satisfy multiple criteria ranges.",
    category: "Math",
  },
  {
    name: "SIGN",
    signature: "SIGN(number)",
    description: "Returns -1, 0, or 1 for the sign of a number.",
    category: "Math",
  },
  {
    name: "TRUNC",
    signature: "TRUNC(number, [digits])",
    description: "Truncates a number to a fixed number of digits.",
    category: "Math",
  },
  {
    name: "MROUND",
    signature: "MROUND(number, multiple)",
    description: "Rounds a number to the nearest multiple.",
    category: "Math",
  },
  {
    name: "ODD",
    signature: "ODD(number)",
    description: "Rounds a number away from zero to an odd integer.",
    category: "Math",
  },
  {
    name: "EVEN",
    signature: "EVEN(number)",
    description: "Rounds a number away from zero to an even integer.",
    category: "Math",
  },
  {
    name: "RAND",
    signature: "RAND()",
    description: "Returns a random number from 0 to 1.",
    category: "Math",
  },
  {
    name: "RANDBETWEEN",
    signature: "RANDBETWEEN(bottom, top)",
    description: "Returns a random integer between two bounds.",
    category: "Math",
  },
];
