import type { SpreadsheetFormulaFunction } from "./spreadsheetFormulaTypes";

export const SPREADSHEET_FINANCIAL_FORMULA_FUNCTIONS: SpreadsheetFormulaFunction[] = [
  {
    name: "PV",
    signature: "PV(rate, nper, pmt, [fv], [type])",
    description: "Returns the present value for an investment or loan.",
    category: "Financial",
  },
  {
    name: "FV",
    signature: "FV(rate, nper, pmt, [pv], [type])",
    description: "Returns the future value for an investment or loan.",
    category: "Financial",
  },
  {
    name: "NPER",
    signature: "NPER(rate, pmt, pv, [fv], [type])",
    description: "Returns the number of payment periods.",
    category: "Financial",
  },
  {
    name: "RATE",
    signature: "RATE(nper, pmt, pv, [fv], [type], [guess])",
    description: "Returns the interest rate per period.",
    category: "Financial",
  },
  {
    name: "NPV",
    signature: "NPV(rate, value1, [value2], ...)",
    description: "Returns the net present value of periodic cash flows.",
    category: "Financial",
  },
  {
    name: "IRR",
    signature: "IRR(values, [guess])",
    description: "Returns the internal rate of return for periodic cash flows.",
    category: "Financial",
  },
  {
    name: "MIRR",
    signature: "MIRR(values, finance_rate, reinvest_rate)",
    description: "Returns the modified internal rate of return for cash flows.",
    category: "Financial",
  },
  {
    name: "PMT",
    signature: "PMT(rate, nper, pv, [fv], [type])",
    description: "Returns the periodic payment for a loan.",
    category: "Financial",
  },
  {
    name: "IPMT",
    signature: "IPMT(rate, per, nper, pv, [fv], [type])",
    description: "Returns the interest portion of a payment period.",
    category: "Financial",
  },
  {
    name: "PPMT",
    signature: "PPMT(rate, per, nper, pv, [fv], [type])",
    description: "Returns the principal portion of a payment period.",
    category: "Financial",
  },
  {
    name: "CUMIPMT",
    signature: "CUMIPMT(rate, nper, pv, start_period, end_period, type)",
    description: "Returns cumulative interest paid across a period range.",
    category: "Financial",
  },
  {
    name: "CUMPRINC",
    signature: "CUMPRINC(rate, nper, pv, start_period, end_period, type)",
    description: "Returns cumulative principal paid across a period range.",
    category: "Financial",
  },
  {
    name: "SLN",
    signature: "SLN(cost, salvage, life)",
    description: "Returns straight-line depreciation for one period.",
    category: "Financial",
  },
  {
    name: "SYD",
    signature: "SYD(cost, salvage, life, per)",
    description: "Returns sum-of-years depreciation for a period.",
    category: "Financial",
  },
  {
    name: "DB",
    signature: "DB(cost, salvage, life, period, [month])",
    description: "Returns fixed-declining balance depreciation for a period.",
    category: "Financial",
  },
  {
    name: "DDB",
    signature: "DDB(cost, salvage, life, period, [factor])",
    description: "Returns double-declining balance depreciation for a period.",
    category: "Financial",
  },
  {
    name: "EFFECT",
    signature: "EFFECT(nominal_rate, npery)",
    description: "Returns the effective annual interest rate.",
    category: "Financial",
  },
  {
    name: "NOMINAL",
    signature: "NOMINAL(effect_rate, npery)",
    description: "Returns the nominal annual interest rate.",
    category: "Financial",
  },
  {
    name: "RRI",
    signature: "RRI(nper, pv, fv)",
    description: "Returns an equivalent growth rate for an investment.",
    category: "Financial",
  },
];

export const SPREADSHEET_ENGINEERING_FORMULA_FUNCTIONS: SpreadsheetFormulaFunction[] = [
  {
    name: "BIN2DEC",
    signature: "BIN2DEC(number)",
    description: "Converts a binary number to decimal.",
    category: "Engineering",
  },
  {
    name: "BIN2HEX",
    signature: "BIN2HEX(number, [places])",
    description: "Converts a binary number to hexadecimal text.",
    category: "Engineering",
  },
  {
    name: "BIN2OCT",
    signature: "BIN2OCT(number, [places])",
    description: "Converts a binary number to octal text.",
    category: "Engineering",
  },
  {
    name: "DEC2BIN",
    signature: "DEC2BIN(number, [places])",
    description: "Converts a decimal number to binary text.",
    category: "Engineering",
  },
  {
    name: "HEX2DEC",
    signature: "HEX2DEC(number)",
    description: "Converts a hexadecimal number to decimal.",
    category: "Engineering",
  },
  {
    name: "HEX2BIN",
    signature: "HEX2BIN(number, [places])",
    description: "Converts a hexadecimal number to binary text.",
    category: "Engineering",
  },
  {
    name: "HEX2OCT",
    signature: "HEX2OCT(number, [places])",
    description: "Converts a hexadecimal number to octal text.",
    category: "Engineering",
  },
  {
    name: "DEC2HEX",
    signature: "DEC2HEX(number, [places])",
    description: "Converts a decimal number to hexadecimal text.",
    category: "Engineering",
  },
  {
    name: "OCT2DEC",
    signature: "OCT2DEC(number)",
    description: "Converts an octal number to decimal.",
    category: "Engineering",
  },
  {
    name: "OCT2BIN",
    signature: "OCT2BIN(number, [places])",
    description: "Converts an octal number to binary text.",
    category: "Engineering",
  },
  {
    name: "OCT2HEX",
    signature: "OCT2HEX(number, [places])",
    description: "Converts an octal number to hexadecimal text.",
    category: "Engineering",
  },
  {
    name: "DEC2OCT",
    signature: "DEC2OCT(number, [places])",
    description: "Converts a decimal number to octal text.",
    category: "Engineering",
  },
  {
    name: "BITAND",
    signature: "BITAND(number1, number2)",
    description: "Returns the bitwise AND of two non-negative integers.",
    category: "Engineering",
  },
  {
    name: "BITOR",
    signature: "BITOR(number1, number2)",
    description: "Returns the bitwise OR of two non-negative integers.",
    category: "Engineering",
  },
  {
    name: "BITXOR",
    signature: "BITXOR(number1, number2)",
    description: "Returns the bitwise XOR of two non-negative integers.",
    category: "Engineering",
  },
  {
    name: "BITLSHIFT",
    signature: "BITLSHIFT(number, shift_amount)",
    description: "Returns a number shifted left by bits.",
    category: "Engineering",
  },
  {
    name: "BITRSHIFT",
    signature: "BITRSHIFT(number, shift_amount)",
    description: "Returns a number shifted right by bits.",
    category: "Engineering",
  },
  {
    name: "DELTA",
    signature: "DELTA(number1, [number2])",
    description: "Returns 1 when two numbers are equal, otherwise 0.",
    category: "Engineering",
  },
  {
    name: "GESTEP",
    signature: "GESTEP(number, [step])",
    description: "Returns 1 when a number is greater than or equal to a step.",
    category: "Engineering",
  },
  {
    name: "CONVERT",
    signature: "CONVERT(number, from_unit, to_unit)",
    description: "Converts compatible length, mass, time, volume, area, and temperature units.",
    category: "Engineering",
  },
];
