import type { SpreadsheetFormulaFunction } from "./spreadsheetFormula";

export const SPREADSHEET_FORMULA_FUNCTIONS: SpreadsheetFormulaFunction[] = [
  {
    name: "SUM",
    signature: "SUM(number1, [number2], ...)",
    description: "Adds numbers, cell references, and ranges.",
    category: "Math",
  },
  {
    name: "AVERAGE",
    signature: "AVERAGE(number1, [number2], ...)",
    description: "Returns the arithmetic mean of numeric arguments.",
    category: "Math",
  },
  {
    name: "AVERAGEIF",
    signature: "AVERAGEIF(range, criteria, [average_range])",
    description: "Averages values whose matching range entries satisfy a criteria expression.",
    category: "Statistical",
  },
  {
    name: "AVERAGEIFS",
    signature: "AVERAGEIFS(average_range, criteria_range1, criteria1, ...)",
    description: "Averages values that satisfy multiple criteria ranges.",
    category: "Statistical",
  },
  {
    name: "COUNT",
    signature: "COUNT(value1, [value2], ...)",
    description: "Counts numeric values.",
    category: "Math",
  },
  {
    name: "COUNTIF",
    signature: "COUNTIF(range, criteria)",
    description: "Counts values that satisfy a criteria expression.",
    category: "Statistical",
  },
  {
    name: "COUNTIFS",
    signature: "COUNTIFS(criteria_range1, criteria1, ...)",
    description: "Counts rows that satisfy multiple criteria ranges.",
    category: "Statistical",
  },
  {
    name: "COUNTA",
    signature: "COUNTA(value1, [value2], ...)",
    description: "Counts non-empty values.",
    category: "Math",
  },
  {
    name: "MIN",
    signature: "MIN(number1, [number2], ...)",
    description: "Returns the smallest numeric value.",
    category: "Math",
  },
  {
    name: "MAX",
    signature: "MAX(number1, [number2], ...)",
    description: "Returns the largest numeric value.",
    category: "Math",
  },
  {
    name: "ABS",
    signature: "ABS(number)",
    description: "Returns the absolute value.",
    category: "Math",
  },
  {
    name: "ROUND",
    signature: "ROUND(number, digits)",
    description: "Rounds a number to a fixed number of digits.",
    category: "Math",
  },
  {
    name: "ROUNDUP",
    signature: "ROUNDUP(number, digits)",
    description: "Rounds a number away from zero.",
    category: "Math",
  },
  {
    name: "ROUNDDOWN",
    signature: "ROUNDDOWN(number, digits)",
    description: "Rounds a number toward zero.",
    category: "Math",
  },
  {
    name: "POWER",
    signature: "POWER(number, power)",
    description: "Raises a number to a power.",
    category: "Math",
  },
  {
    name: "SQRT",
    signature: "SQRT(number)",
    description: "Returns the square root.",
    category: "Math",
  },
  {
    name: "PRODUCT",
    signature: "PRODUCT(number1, [number2], ...)",
    description: "Multiplies numeric arguments.",
    category: "Math",
  },
  {
    name: "MEDIAN",
    signature: "MEDIAN(number1, [number2], ...)",
    description: "Returns the median numeric value.",
    category: "Math",
  },
  {
    name: "MOD",
    signature: "MOD(number, divisor)",
    description: "Returns the remainder after division.",
    category: "Math",
  },
  {
    name: "INT",
    signature: "INT(number)",
    description: "Rounds a number down to the nearest integer.",
    category: "Math",
  },
  {
    name: "CEILING",
    signature: "CEILING(number, [significance])",
    description: "Rounds a number up to a multiple.",
    category: "Math",
  },
  {
    name: "FLOOR",
    signature: "FLOOR(number, [significance])",
    description: "Rounds a number down to a multiple.",
    category: "Math",
  },
  {
    name: "SUMSQ",
    signature: "SUMSQ(number1, [number2], ...)",
    description: "Returns the sum of squares.",
    category: "Math",
  },
  {
    name: "SUMIF",
    signature: "SUMIF(range, criteria, [sum_range])",
    description: "Adds values whose matching range entries satisfy a criteria expression.",
    category: "Math",
  },
  {
    name: "SUMIFS",
    signature: "SUMIFS(sum_range, criteria_range1, criteria1, ...)",
    description: "Adds values that satisfy multiple criteria ranges.",
    category: "Math",
  },
  {
    name: "SIGN",
    signature: "SIGN(number)",
    description: "Returns -1, 0, or 1 for the sign of a number.",
    category: "Math",
  },
  {
    name: "TRUNC",
    signature: "TRUNC(number, [digits])",
    description: "Truncates a number to a fixed number of digits.",
    category: "Math",
  },
  {
    name: "MROUND",
    signature: "MROUND(number, multiple)",
    description: "Rounds a number to the nearest multiple.",
    category: "Math",
  },
  {
    name: "ODD",
    signature: "ODD(number)",
    description: "Rounds a number away from zero to an odd integer.",
    category: "Math",
  },
  {
    name: "EVEN",
    signature: "EVEN(number)",
    description: "Rounds a number away from zero to an even integer.",
    category: "Math",
  },
  {
    name: "RAND",
    signature: "RAND()",
    description: "Returns a random number from 0 to 1.",
    category: "Math",
  },
  {
    name: "RANDBETWEEN",
    signature: "RANDBETWEEN(bottom, top)",
    description: "Returns a random integer between two bounds.",
    category: "Math",
  },
  {
    name: "COUNTBLANK",
    signature: "COUNTBLANK(range)",
    description: "Counts blank values in the supplied values or ranges.",
    category: "Statistical",
  },
  {
    name: "STDEV.S",
    signature: "STDEV.S(number1, [number2], ...)",
    description: "Returns sample standard deviation.",
    category: "Statistical",
  },
  {
    name: "STDEV.P",
    signature: "STDEV.P(number1, [number2], ...)",
    description: "Returns population standard deviation.",
    category: "Statistical",
  },
  {
    name: "VAR.S",
    signature: "VAR.S(number1, [number2], ...)",
    description: "Returns sample variance.",
    category: "Statistical",
  },
  {
    name: "VAR.P",
    signature: "VAR.P(number1, [number2], ...)",
    description: "Returns population variance.",
    category: "Statistical",
  },
  {
    name: "LARGE",
    signature: "LARGE(array, k)",
    description: "Returns the k-th largest numeric value.",
    category: "Statistical",
  },
  {
    name: "SMALL",
    signature: "SMALL(array, k)",
    description: "Returns the k-th smallest numeric value.",
    category: "Statistical",
  },
  {
    name: "PERCENTILE.INC",
    signature: "PERCENTILE.INC(array, k)",
    description: "Returns an inclusive percentile.",
    category: "Statistical",
  },
  {
    name: "QUARTILE.INC",
    signature: "QUARTILE.INC(array, quart)",
    description: "Returns an inclusive quartile.",
    category: "Statistical",
  },
  {
    name: "IF",
    signature: "IF(test, value_if_true, value_if_false)",
    description: "Returns one value when a condition is true and another when false.",
    category: "Logical",
  },
  {
    name: "AND",
    signature: "AND(condition1, [condition2], ...)",
    description: "Returns TRUE when every argument is true.",
    category: "Logical",
  },
  {
    name: "OR",
    signature: "OR(condition1, [condition2], ...)",
    description: "Returns TRUE when any argument is true.",
    category: "Logical",
  },
  {
    name: "NOT",
    signature: "NOT(condition)",
    description: "Reverses a logical value.",
    category: "Logical",
  },
  {
    name: "TRUE",
    signature: "TRUE()",
    description: "Returns the logical value TRUE.",
    category: "Logical",
  },
  {
    name: "FALSE",
    signature: "FALSE()",
    description: "Returns the logical value FALSE.",
    category: "Logical",
  },
  {
    name: "XOR",
    signature: "XOR(condition1, [condition2], ...)",
    description: "Returns TRUE when an odd number of arguments are true.",
    category: "Logical",
  },
  {
    name: "IFERROR",
    signature: "IFERROR(value, value_if_error)",
    description: "Returns a fallback when the first value is an error.",
    category: "Logical",
  },
  {
    name: "IFNA",
    signature: "IFNA(value, value_if_na)",
    description: "Returns a fallback when the first value is #N/A.",
    category: "Logical",
  },
  {
    name: "IFS",
    signature: "IFS(test1, value1, [test2, value2], ...)",
    description: "Returns the value for the first TRUE condition.",
    category: "Logical",
  },
  {
    name: "SWITCH",
    signature: "SWITCH(expression, value1, result1, ..., [default])",
    description: "Matches an expression against values and returns a result.",
    category: "Logical",
  },
  {
    name: "LEN",
    signature: "LEN(text)",
    description: "Returns the number of characters in text.",
    category: "Text",
  },
  {
    name: "CONCAT",
    signature: "CONCAT(value1, [value2], ...)",
    description: "Joins values into one text value.",
    category: "Text",
  },
  {
    name: "CONCATENATE",
    signature: "CONCATENATE(value1, [value2], ...)",
    description: "Joins values into one text value.",
    category: "Text",
  },
  {
    name: "TEXTJOIN",
    signature: "TEXTJOIN(delimiter, ignore_empty, text1, ...)",
    description: "Joins text values with a delimiter.",
    category: "Text",
  },
  {
    name: "LEFT",
    signature: "LEFT(text, [count])",
    description: "Returns characters from the start of text.",
    category: "Text",
  },
  {
    name: "RIGHT",
    signature: "RIGHT(text, [count])",
    description: "Returns characters from the end of text.",
    category: "Text",
  },
  {
    name: "MID",
    signature: "MID(text, start, count)",
    description: "Returns characters from the middle of text.",
    category: "Text",
  },
  {
    name: "LOWER",
    signature: "LOWER(text)",
    description: "Converts text to lowercase.",
    category: "Text",
  },
  {
    name: "UPPER",
    signature: "UPPER(text)",
    description: "Converts text to uppercase.",
    category: "Text",
  },
  {
    name: "TRIM",
    signature: "TRIM(text)",
    description: "Removes extra spaces from text.",
    category: "Text",
  },
  {
    name: "SUBSTITUTE",
    signature: "SUBSTITUTE(text, old_text, new_text, [instance])",
    description: "Replaces matching text occurrences.",
    category: "Text",
  },
  {
    name: "REPLACE",
    signature: "REPLACE(old_text, start, count, new_text)",
    description: "Replaces a character range in text.",
    category: "Text",
  },
  {
    name: "FIND",
    signature: "FIND(find_text, within_text, [start])",
    description: "Finds case-sensitive text and returns a 1-based position.",
    category: "Text",
  },
  {
    name: "SEARCH",
    signature: "SEARCH(find_text, within_text, [start])",
    description: "Finds text case-insensitively and returns a 1-based position.",
    category: "Text",
  },
  {
    name: "EXACT",
    signature: "EXACT(text1, text2)",
    description: "Returns TRUE when two text values match exactly.",
    category: "Text",
  },
  {
    name: "VALUE",
    signature: "VALUE(text)",
    description: "Converts a text value to a number.",
    category: "Text",
  },
  {
    name: "NUMBERVALUE",
    signature: "NUMBERVALUE(text, [decimal_separator], [group_separator])",
    description: "Converts localized numeric text to a number.",
    category: "Text",
  },
  {
    name: "CLEAN",
    signature: "CLEAN(text)",
    description: "Removes non-printable control characters.",
    category: "Text",
  },
  {
    name: "TEXTBEFORE",
    signature: "TEXTBEFORE(text, delimiter)",
    description: "Returns text before a delimiter.",
    category: "Text",
  },
  {
    name: "TEXTAFTER",
    signature: "TEXTAFTER(text, delimiter)",
    description: "Returns text after a delimiter.",
    category: "Text",
  },
  {
    name: "TODAY",
    signature: "TODAY()",
    description: "Returns the current date as an Excel serial number.",
    category: "Date",
  },
  {
    name: "NOW",
    signature: "NOW()",
    description: "Returns the current date and time as an Excel serial number.",
    category: "Date",
  },
  {
    name: "DATE",
    signature: "DATE(year, month, day)",
    description: "Builds an Excel date serial number.",
    category: "Date",
  },
  {
    name: "YEAR",
    signature: "YEAR(serial_number)",
    description: "Returns the year from an Excel date serial number.",
    category: "Date",
  },
  {
    name: "MONTH",
    signature: "MONTH(serial_number)",
    description: "Returns the month from an Excel date serial number.",
    category: "Date",
  },
  {
    name: "DAY",
    signature: "DAY(serial_number)",
    description: "Returns the day of month from an Excel date serial number.",
    category: "Date",
  },
  {
    name: "HOUR",
    signature: "HOUR(serial_number)",
    description: "Returns the hour from an Excel date/time serial number.",
    category: "Date",
  },
  {
    name: "MINUTE",
    signature: "MINUTE(serial_number)",
    description: "Returns the minute from an Excel date/time serial number.",
    category: "Date",
  },
  {
    name: "SECOND",
    signature: "SECOND(serial_number)",
    description: "Returns the second from an Excel date/time serial number.",
    category: "Date",
  },
  {
    name: "DAYS",
    signature: "DAYS(end_date, start_date)",
    description: "Returns the number of days between two date serial numbers.",
    category: "Date",
  },
  {
    name: "TIME",
    signature: "TIME(hour, minute, second)",
    description: "Returns an Excel time serial fraction.",
    category: "Date",
  },
  {
    name: "DATEVALUE",
    signature: "DATEVALUE(date_text)",
    description: "Converts date text to an Excel date serial number.",
    category: "Date",
  },
  {
    name: "WEEKDAY",
    signature: "WEEKDAY(serial_number, [return_type])",
    description: "Returns the day of week for a date serial.",
    category: "Date",
  },
  {
    name: "EOMONTH",
    signature: "EOMONTH(start_date, months)",
    description: "Returns the serial date for the last day of a month offset.",
    category: "Date",
  },
  {
    name: "INDEX",
    signature: "INDEX(array, row_num, [column_num])",
    description: "Returns a value from a range by row and column.",
    category: "Lookup",
  },
  {
    name: "MATCH",
    signature: "MATCH(lookup_value, lookup_array, [match_type])",
    description: "Returns the 1-based position of a lookup value.",
    category: "Lookup",
  },
  {
    name: "XMATCH",
    signature: "XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])",
    description: "Returns the 1-based position of a lookup value with search options.",
    category: "Lookup",
  },
  {
    name: "XLOOKUP",
    signature: "XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found])",
    description: "Looks up a value and returns the corresponding result.",
    category: "Lookup",
  },
  {
    name: "VLOOKUP",
    signature: "VLOOKUP(lookup_value, table_array, col_index, [range_lookup])",
    description: "Looks down the first table column and returns a value from another column.",
    category: "Lookup",
  },
  {
    name: "HLOOKUP",
    signature: "HLOOKUP(lookup_value, table_array, row_index, [range_lookup])",
    description: "Looks across the first table row and returns a value from another row.",
    category: "Lookup",
  },
  {
    name: "CHOOSE",
    signature: "CHOOSE(index_num, value1, [value2], ...)",
    description: "Returns a value selected by 1-based index.",
    category: "Lookup",
  },
  {
    name: "FILTER",
    signature: "FILTER(array, include, [if_empty])",
    description: "Returns values where the include array is TRUE.",
    category: "Lookup",
  },
  {
    name: "UNIQUE",
    signature: "UNIQUE(array)",
    description: "Returns unique values from a range.",
    category: "Lookup",
  },
  {
    name: "SORT",
    signature: "SORT(array, [sort_index], [sort_order])",
    description: "Sorts a range by row values.",
    category: "Lookup",
  },
  {
    name: "ISBLANK",
    signature: "ISBLANK(value)",
    description: "Returns TRUE when the value is blank.",
    category: "Information",
  },
  {
    name: "ISNUMBER",
    signature: "ISNUMBER(value)",
    description: "Returns TRUE when the value is numeric.",
    category: "Information",
  },
  {
    name: "ISTEXT",
    signature: "ISTEXT(value)",
    description: "Returns TRUE when the value is text.",
    category: "Information",
  },
  {
    name: "ISERROR",
    signature: "ISERROR(value)",
    description: "Returns TRUE when the value is any spreadsheet error.",
    category: "Information",
  },
  {
    name: "ISNA",
    signature: "ISNA(value)",
    description: "Returns TRUE when the value is #N/A.",
    category: "Information",
  },
  {
    name: "PV",
    signature: "PV(rate, nper, pmt, [fv], [type])",
    description: "Returns the present value for an investment or loan.",
    category: "Financial",
  },
  {
    name: "FV",
    signature: "FV(rate, nper, pmt, [pv], [type])",
    description: "Returns the future value for an investment or loan.",
    category: "Financial",
  },
  {
    name: "NPER",
    signature: "NPER(rate, pmt, pv, [fv], [type])",
    description: "Returns the number of payment periods.",
    category: "Financial",
  },
  {
    name: "RATE",
    signature: "RATE(nper, pmt, pv, [fv], [type], [guess])",
    description: "Returns the interest rate per period.",
    category: "Financial",
  },
  {
    name: "NPV",
    signature: "NPV(rate, value1, [value2], ...)",
    description: "Returns the net present value of periodic cash flows.",
    category: "Financial",
  },
  {
    name: "IRR",
    signature: "IRR(values, [guess])",
    description: "Returns the internal rate of return for periodic cash flows.",
    category: "Financial",
  },
  {
    name: "MIRR",
    signature: "MIRR(values, finance_rate, reinvest_rate)",
    description: "Returns the modified internal rate of return for cash flows.",
    category: "Financial",
  },
  {
    name: "PMT",
    signature: "PMT(rate, nper, pv, [fv], [type])",
    description: "Returns the periodic payment for a loan.",
    category: "Financial",
  },
  {
    name: "IPMT",
    signature: "IPMT(rate, per, nper, pv, [fv], [type])",
    description: "Returns the interest portion of a payment period.",
    category: "Financial",
  },
  {
    name: "PPMT",
    signature: "PPMT(rate, per, nper, pv, [fv], [type])",
    description: "Returns the principal portion of a payment period.",
    category: "Financial",
  },
  {
    name: "CUMIPMT",
    signature: "CUMIPMT(rate, nper, pv, start_period, end_period, type)",
    description: "Returns cumulative interest paid across a period range.",
    category: "Financial",
  },
  {
    name: "CUMPRINC",
    signature: "CUMPRINC(rate, nper, pv, start_period, end_period, type)",
    description: "Returns cumulative principal paid across a period range.",
    category: "Financial",
  },
  {
    name: "SLN",
    signature: "SLN(cost, salvage, life)",
    description: "Returns straight-line depreciation for one period.",
    category: "Financial",
  },
  {
    name: "SYD",
    signature: "SYD(cost, salvage, life, per)",
    description: "Returns sum-of-years depreciation for a period.",
    category: "Financial",
  },
  {
    name: "DB",
    signature: "DB(cost, salvage, life, period, [month])",
    description: "Returns fixed-declining balance depreciation for a period.",
    category: "Financial",
  },
  {
    name: "DDB",
    signature: "DDB(cost, salvage, life, period, [factor])",
    description: "Returns double-declining balance depreciation for a period.",
    category: "Financial",
  },
  {
    name: "EFFECT",
    signature: "EFFECT(nominal_rate, npery)",
    description: "Returns the effective annual interest rate.",
    category: "Financial",
  },
  {
    name: "NOMINAL",
    signature: "NOMINAL(effect_rate, npery)",
    description: "Returns the nominal annual interest rate.",
    category: "Financial",
  },
  {
    name: "RRI",
    signature: "RRI(nper, pv, fv)",
    description: "Returns an equivalent growth rate for an investment.",
    category: "Financial",
  },
  {
    name: "BIN2DEC",
    signature: "BIN2DEC(number)",
    description: "Converts a binary number to decimal.",
    category: "Engineering",
  },
  {
    name: "BIN2HEX",
    signature: "BIN2HEX(number, [places])",
    description: "Converts a binary number to hexadecimal text.",
    category: "Engineering",
  },
  {
    name: "BIN2OCT",
    signature: "BIN2OCT(number, [places])",
    description: "Converts a binary number to octal text.",
    category: "Engineering",
  },
  {
    name: "DEC2BIN",
    signature: "DEC2BIN(number, [places])",
    description: "Converts a decimal number to binary text.",
    category: "Engineering",
  },
  {
    name: "HEX2DEC",
    signature: "HEX2DEC(number)",
    description: "Converts a hexadecimal number to decimal.",
    category: "Engineering",
  },
  {
    name: "HEX2BIN",
    signature: "HEX2BIN(number, [places])",
    description: "Converts a hexadecimal number to binary text.",
    category: "Engineering",
  },
  {
    name: "HEX2OCT",
    signature: "HEX2OCT(number, [places])",
    description: "Converts a hexadecimal number to octal text.",
    category: "Engineering",
  },
  {
    name: "DEC2HEX",
    signature: "DEC2HEX(number, [places])",
    description: "Converts a decimal number to hexadecimal text.",
    category: "Engineering",
  },
  {
    name: "OCT2DEC",
    signature: "OCT2DEC(number)",
    description: "Converts an octal number to decimal.",
    category: "Engineering",
  },
  {
    name: "OCT2BIN",
    signature: "OCT2BIN(number, [places])",
    description: "Converts an octal number to binary text.",
    category: "Engineering",
  },
  {
    name: "OCT2HEX",
    signature: "OCT2HEX(number, [places])",
    description: "Converts an octal number to hexadecimal text.",
    category: "Engineering",
  },
  {
    name: "DEC2OCT",
    signature: "DEC2OCT(number, [places])",
    description: "Converts a decimal number to octal text.",
    category: "Engineering",
  },
  {
    name: "BITAND",
    signature: "BITAND(number1, number2)",
    description: "Returns the bitwise AND of two non-negative integers.",
    category: "Engineering",
  },
  {
    name: "BITOR",
    signature: "BITOR(number1, number2)",
    description: "Returns the bitwise OR of two non-negative integers.",
    category: "Engineering",
  },
  {
    name: "BITXOR",
    signature: "BITXOR(number1, number2)",
    description: "Returns the bitwise XOR of two non-negative integers.",
    category: "Engineering",
  },
  {
    name: "BITLSHIFT",
    signature: "BITLSHIFT(number, shift_amount)",
    description: "Returns a number shifted left by bits.",
    category: "Engineering",
  },
  {
    name: "BITRSHIFT",
    signature: "BITRSHIFT(number, shift_amount)",
    description: "Returns a number shifted right by bits.",
    category: "Engineering",
  },
  {
    name: "DELTA",
    signature: "DELTA(number1, [number2])",
    description: "Returns 1 when two numbers are equal, otherwise 0.",
    category: "Engineering",
  },
  {
    name: "GESTEP",
    signature: "GESTEP(number, [step])",
    description: "Returns 1 when a number is greater than or equal to a step.",
    category: "Engineering",
  },
  {
    name: "CONVERT",
    signature: "CONVERT(number, from_unit, to_unit)",
    description: "Converts compatible length, mass, time, volume, area, and temperature units.",
    category: "Engineering",
  },
];
